### ISSUE TITLE
`session.done()` hangs on `queue.join()`

### ISSUE THREAD

**Issue by ASalvail** [Losswise/losswise-python#2]
There doesn't seem to be a timeout for some operation and the call to `session.done()` hangs indefinitely.

Jobs eventually appear as `Cancelled` on the dashboard.

**Comment by nicodjimenez** [comment]
Thanks for pointing this out, this is caused by the request queue getting pilled up due to logging to Losswise too frequently.   Will address this ASAP by flushing updates (instead of doing one request per point, batching them together).

**Comment by nicodjimenez** [comment]
@ASalvail this issue should be resolved now, just do `pip install --upgrade losswise` and you should be good to go.  

Let me know if that fixes the issue for you.  

I will note that the graphs still don't update super smoothly if you log new points to Losswise more than 3 times for second (batching updates to the graphs needs more work) but the summary table and the Python client now work smoothly even if you log data very rapidly, which definitely wasn't the case before.
