### ISSUE TITLE
question about your blog about LSTM

### ISSUE THREAD

**Issue by frozenxia** [Losswise/losswise-python#8]
Sorry for create an issue in this project and thanks for your great work on the blog about lstm(http://nicodjimenez.github.io/2014/08/08/lstm.html) .  I am afraid that you have already deprecated the project of lstm (https://github.com/nicodjimenez/lstm) ,so i open an issue here.
Sorry for this again.

 in your blog (http://nicodjimenez.github.io/2014/08/08/lstm.html),  derivative of s(t) is get by this equation,
![image](https://user-images.githubusercontent.com/5286725/36954928-1eb2c4b4-2060-11e8-85ac-5aa3079e977d.png)
i wonder why the left of this equation is equal to the right. 
in my opinion, left = 0.5*right. and why we need the **top_diff_s** if we could calculate 
![image](https://user-images.githubusercontent.com/5286725/36970008-08f0c53a-20a2-11e8-8082-67b81d9cbc5d.png) directly.
![image](https://user-images.githubusercontent.com/5286725/36970071-407979de-20a2-11e8-8686-6b07c3fa4e15.png)

I am new to nn and lstm,  and i will appreciate if you could give some tips on this question, thanks!

**Comment by nicodjimenez** [comment]
Hi, thanks for reaching out! Let's continue this discussion on the LSTM blog.
