### ISSUE TITLE
Make git diff optional

### ISSUE THREAD

**Issue by jgc128** [Losswise/losswise-python#9]
Hi,

Thank you for such a great service! 
I really like, but there are several issues with how it tries to send `git diff` to the server:

 1. Some people would not want their code to be submitted to an arbitrary server on the internet
 2. When git diff returns a very big message, the client (v1.9) crashes with the following error:

```
  File "./lib/python3.6/site-packages/losswise/__init__.py", line 192, in __init__
    json_resp = r.json()
  File "./lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "./lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "./lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "./lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``` 

The status code 413, which is `HTTP 413 Payload Too Large`

**Comment by nicodjimenez** [comment]
Thanks a lot for the error report.  Making git tracking optional is important, as well as making the allowable payloads larger.

**Comment by nicodjimenez** [comment]
Point number one has been addressed by the new version (see https://docs.losswise.com/#sessions too).  Point two is a server side issue and will be addressed elsewhere ASAP.  Let me know if you have any issue with the current implementation.

**Comment by jgc128** [comment]
Great! Thank you very much!
